name: IaC Security

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Checkov
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            bridgecrew/checkov:latest \
            -d /src \
            --soft-fail-on LOW,MEDIUM \
            --hard-fail-on HIGH


  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run tfsec
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            aquasec/tfsec:latest \
            /src/terraform \
            --minimum-severity HIGH


  kics:
    name: KICS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run KICS
        run: |
          docker run --rm \
            -v "$PWD:/path" \
            checkmarx/kics:latest \
            scan \
            -p /path/terraform \
            --fail-on high
